version: "3"
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=___
      - POSTGRES_PASSWORD=____
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    container_name: jlcbot
    links:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
